version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=bookstore
      - POSTGRES_USER=gokaygok
      - POSTGRES_PASSWORD=12345
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bookstore
      - POSTGRES_USER=gokaygok
      - POSTGRES_PASSWORD=12345
    depends_on:
      - db