# Generated by Django 3.2.6 on 2021-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/%d'),
        ),
    ]
