# Generated by Django 3.2.6 on 2022-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220304_0259'),
        ('profile', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='book.Book'),
        ),
    ]
